Убрал не используемые методы и переменные, подкорректировал недочеты.
Vanguard477/Cs2 pull request #3
Opened 2024-11-20 18:28 UTC by Vanguard477

2024-11-20 19:14 UTC, revinsd requested changes

2024-11-20 19:14 UTC, revinsd commented on src/main/java/com/trade/cs2/service/UserService.java
>      UserRepository userRepository;
Тут и ниже поля приватные сделай

2024-11-20 19:14 UTC, revinsd commented on src/main/java/com/trade/cs2/service/UserService.java
> +        User user = userRepository.findByUsername(username)
давай в 1 строку сделаем, return userReposity.findByUserName........

2024-11-20 19:14 UTC, revinsd commented on src/main/java/com/trade/cs2/service/UserService.java
> +        Optional<User> userFromDB = userRepository.findByUsername(user.getUsername());
Давай еще лучше сделаем, в репозиторий добавь метод existsByUsername, который будет проверять наличие пользователя в бд

2024-11-21 09:48 UTC, Vanguard477 commented on src/main/java/com/trade/cs2/service/UserService.java
>      UserRepository userRepository;
+

2024-11-22 13:19 UTC, Vanguard477 commented on src/main/java/com/trade/cs2/service/UserService.java
> +        User user = userRepository.findByUsername(username)
+

2024-11-24 18:06 UTC, merged